### PR TITLE
Trackprogress fix #199

### LINKED ISSUE #199: Tracking Progress
The "Tracking Progress" page is missing the items below:

### Directions

1. Number of Comments made

### Progress

1. Number of Comments made

### PR DESCRIPTION
**Pull request by sonAndrew**
Fixed local repo. Added function that gets "total comments"

https://raw.githack.com/sonAndrew/sonAndrew.github.io/trackprogress/#!pages/vi/trackprogress.md

### CODE REVIEW

**Review by CalebProvost — APPROVED** [review]
Good work on the comment code! The only problem I've found is the count is incorrect.
That and spamming the function causes it to stop working. Don't think that's your code, I think its an api limitation.
👍 Good start!

**Comment by CalebProvost** [comment]
~~Testing further. It currently says 16 comments. I'll thumbs up this comment if it says 17 after I post it.~~

---
https://github.com/treehouses/treehouses.github.io/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aissue+commenter%3ACalebProvost
The above link demonstrates that it should be 45+

**Comment by sriharivishnu** [comment]
@sonAndrew use this query instead of `type:comment`: `"https://api.github.com/search/issues?q=repo:treehouses/treehouses.github.io+commenter:" + user`

**Comment by sriharivishnu** [comment]
@CalebProvost Yeah, I think spamming it induces an API limitation because I got this message: 
```
{
  "message": "API rate limit exceeded for 99.250.64.101. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
```

**Comment by CalebProvost** [comment]
Thanks for all the assists @sriharivishnu 
I've never played with api's before, and definitely not github's api's. Hopefully it helps @sonAndrew progress with this PR.

**Review by CalebProvost — APPROVED** [review]

**Comment by XavierElon** [comment]
Testing this now

**Review by XavierElon — APPROVED** [review]
Worked for me :)

**Pull request merged**
