### PR TITLE
create 20200818-localcodeclimate.md

### PR DESCRIPTION
**Pull request by sydneyaldo**
https://raw.githack.com/treehouses/treehouses.github.io/local-codeclimate/#!pages/blog/20200818-localcodeclimate.md

### CODE REVIEW

**Comment by dogi** [comment]
@sydneyaldo add link of this blog to blog.md

**Review by dogi — APPROVED** [review]

**Review by anastasia21112 — DISMISSED** [review]
Add a note on Step 7 to run codeclimate engines:install before codeclimate analyze if getting the error that the engine timed out

**Review by anthonyhvo12 — DISMISSED** [review]
- Add a note on step 5 that the output may vary on different machines when running 'vagrant up'.
- On step 7, how do we check that codeclimate wrapper is installed inside the usr/local/bin folder?
- Add a note that running structure may take a while, especially on larger folders.

**Comment by sydneyaldo** [comment]
@anastasia21112 @anthonyhvo12 thanks, please see if recent commit fixed them

**Comment by dogi** [comment]
```
vagrant@remote:~$ codeclimate engines:install
Pulling docker images.
Using default tag: latest
latest: Pulling from codeclimate/codeclimate-structure
75cb2ebf3b3c: Pulling fs layer 
bf9f7b182d6c: Pulling fs layer 
...
d072530a3378: Pull complete 
e198cf3b1351: Pull complete 
Digest: sha256:63601288051ac8d71d910dc2cee871bf0d22c5bf7e4a3a66e313ef5047a9f2fe
Status: Downloaded newer image for codeclimate/codeclimate-structure:latest
Using default tag: latest
latest: Pulling from codeclimate/codeclimate-duplication
75cb2ebf3b3c: Already exists 
bf9f7b182d6c: Already exists 
...
cf818c6259f3: Pull complete 
e929626cf0b2: Pull complete 
Digest: sha256:d80a157b3093af6422b5e5ff16b9fc2883c66c435848caf6ac557dd06c83c491
Status: Downloaded newer image for codeclimate/codeclimate-duplication:latest
vagrant@remote:~$ 
```

**Review by anastasia21112 — APPROVED** [review]
looks great

**Review by dogi — APPROVED** [review]

**Pull request merged**
