### PR TITLE
Update 404.md to direct to correct page (fixes #203) 

### LINKED ISSUE #203: "Page not found" link to home goes to different website
When clicking on the **"Go home"** link in the page not found section,

Screen Shot 2019-10-09 at 9 43 41 PM

 instead of going to the home page of treehouses.io, it goes to this website instead.
Screen Shot 2019-10-09 at 9 44 01 PM

I am not sure if this was the intended effect, but I'd recommend linking it back to the treehouses.io home page instead of the OLE website one.

### PR DESCRIPTION
**Pull request by sriharivishnu**
Changed the link of the page that "Go Home" is redirecting to. It now goes to the correct home page.
https://raw.githack.com/sriharivishnu/sriharivishnu.github.io/master/#!./pages/vi/test

### CODE REVIEW

**Comment by pattanawadee88** [comment]
Could you please put the rawgit link for us to review? Thanks!

**Comment by sriharivishnu** [comment]
@pattanawadee88  Sorry about that! Here is the link: https://raw.githack.com/sriharivishnu/sriharivishnu.github.io/master/#!./pages/vi/test

**Review by CalebProvost — APPROVED** [review]

**Review by pattanawadee88 — CHANGES_REQUESTED** [review]
you shouldn't work from your master branch. Please create another branch from your master and work from it :)

**Comment by CalebProvost** [comment]
> you shouldn't work from your master branch. Please create another branch from your master and work from it :)

This might help:
https://www.endpoint.com/blog/2012/06/21/moving-commit-to-another-branch-in-git

**Pull request closed without merging**
