### PR TITLE
create jamjakpa.md

### PR DESCRIPTION
**Pull request by jamjakpa**
I believe this link should fix the issue - it now goes to the rendered page for me.

Fixes #282

### Description
I have created my profile  and created the raw.githack

### Raw.Githack preview link
raw.githack link to page(s) changed.

https://raw.githack.com/jamjakpa/jamjakpa.github.io/jamjakpa_first_bracnch/#!./pages/vi/profiles/jamjakpa.md

I verify that I  used at least 5 different Markdown elements in my profile

### CODE REVIEW

**Review by Nida8930 — DISMISSED** [review]
In your githack link you need to include #! after the slash following your branch name. This will link to a rendered page rather than raw markdown.

**Comment by jamjakpa** [comment]
> In your githack link you need to include #! after the slash following your branch name. This will link to a rendered page rather than raw markdown.

I believe this link should fix the issue - it now goes to the rendered page for me.
https://raw.githack.com/jamjakpa/jamjakpa.github.io/jamjakpa_first_bracnch/#!./pages/vi/profiles/jamjakpa.md

**Comment by pattanawadee88** [comment]
Nice work! But it would be nice if you could add a few more Markdown elements :)

**Comment by jamjakpa** [comment]
> Nice work! But it would be nice if you could add a few more Markdown elements :)

Will do :) How come when i add some markup that it does not apply ?

**Comment by jamjakpa** [comment]
> > Nice work! But it would be nice if you could add a few more Markdown elements :)
> 
> Will do :) How come when i add some markup that it does not apply ?

Ok. I fixed it I made some changes :)

**Review by pattanawadee88 — APPROVED** [review]

**Comment by jamjakpa** [comment]
> In your githack link you need to include #! after the slash following your branch name. This will link to a rendered page rather than raw markdown.

I believe this link should fix the issue - it now goes to the rendered page for me.
https://raw.githack.com/jamjakpa/jamjakpa.github.io/jamjakpa_first_bracnch/#!./pages/vi/profiles/jamjakpa.md

**Comment by jamjakpa** [comment]
> In your githack link you need to include #! after the slash following your branch name. This will link to a rendered page rather than raw markdown.

I believe this link should fix the issue - it now goes to the rendered page for me.
https://raw.githack.com/jamjakpa/jamjakpa.github.io/jamjakpa_first_bracnch/#!./pages/vi/profiles/jamjakpa.md

**Comment by jamjakpa** [comment]
> Nice work! But it would be nice if you could add a few more Markdown elements :)

282
Do i need to wait for another person to review it ?

**Comment by pattanawadee88** [comment]
> > Nice work! But it would be nice if you could add a few more Markdown elements :)
> 
> 282
> Do i need to wait for another person to review it ?

yes :) please be patient

**Comment by jamjakpa** [comment]
> > > Nice work! But it would be nice if you could add a few more Markdown elements :)
> > 
> > 
> > 282
> > Do i need to wait for another person to review it ?
> 
> yes :) please be patient

No problem :)

**Review by dogi — APPROVED** [review]

**Pull request merged**
