### PR TITLE
step6 note (fixes #146)

### LINKED ISSUE #146: punctuation and markdown errors in github-issues.md
**Punctuation Error:** [Create a New Branch](https://treehouses.io/#!./pages/vi/github-issues.md#Create_a_New_Branch)

>To create a new branch, go to your github repo and create it using the same steps as you can see[here](https://help.github.com/en/articles/creating-and-deleting-branches-within-your-repository) (do not delete your branch)

There should be a space between `see` and [`here`](https://help.github.com/en/articles/creating-and-deleting-branches-within-your-repository)

**Markdown Errors:** [Notes](https://treehouses.io/#!./pages/vi/github-issues.md#Preview_Changes_Locally)

Linked above is an example of a markdown error where a note is not being rendered correctly due to the markdown style used.

### PR DESCRIPTION
**Pull request by XavierElon**
Put a space between "see" and "here" as described in the issue #146 

https://raw.githack.com/Xavierh93/Xavierh93.github.io/github-issues/#!./pages/vi/github-issues.md

### CODE REVIEW

**Review by CalebProvost — CHANGES_REQUESTED** [review]
Awesome start @xavierh93.

Keep in mind that issue #146 requires more than just the space:

> **Punctuation Error:** [Create a New Branch](https://treehouses.io/#!./pages/vi/github-issues.md#Create_a_New_Branch)
> 
> > To create a new branch, go to your github repo and create it using the same steps as you can see[here](https://help.github.com/en/articles/creating-and-deleting-branches-within-your-repository) (do not delete your branch)
> 
> There should be a space between `see` and [`here`](https://help.github.com/en/articles/creating-and-deleting-branches-within-your-repository)
> 
> **Markdown Errors:** [Notes](https://treehouses.io/#!./pages/vi/github-issues.md#Preview_Changes_Locally)
> 
> Linked above is an example of a markdown error where a note is not being rendered correctly due to the markdown style used.

Essentially, markdown style will need to be adjusted to remove the table effect and turn it into the note effect. (hint: review [github markdown](https://guides.github.com/features/mastering-markdown/) to find out what is making the table effect; lookup the differences in a .md page which has a note in it, and make a similar change)

**Comment by XavierElon** [comment]
@CalebProvost I'm sorry, I'm having trouble understanding what needs to be fixed. Is it because it shows up on the Github preview differently? Can you clarify what needs to be fixed?

**Comment by CalebProvost** [comment]
@xavierh93 sure.
The notes in the page look like tables:
image
But they should instead look like:
image.

**Comment by XavierElon** [comment]
FInal table has been removed.

https://raw.githack.com/Xavierh93/Xavierh93.github.io/github-issues/#!./pages/vi/github-issues.md

**Review by CalebProvost — APPROVED** [review]
Good job @xavierh93.
Just need two more reviews :)

**Review by iawale — APPROVED** [review]

**Review by dogi — APPROVED** [review]

**Pull request merged**
