### PR TITLE
blog privatebin 

### PR DESCRIPTION
**Pull request by hiroTochigi**
https://raw.githack.com/treehouses/treehouses.github.io/add-privatebin/#!pages/blog/20191009-private-bin.md

### CODE REVIEW

**Comment by hiroTochigi** [comment]
https://raw.githack.com/treehouses/treehouses.github.io/add-privatebin/#!pages/blog/20191000-private-bin.md

**Comment by XavierElon** [comment]
I got stuck on step 3. The commands you listed aren't working and I'm not sure why.
Screen Shot 2019-10-11 at 11 13 48 PM

**Comment by hiroTochigi** [comment]
New URL
https://raw.githack.com/treehouses/treehouses.github.io/add-privatebin/#!pages/blog/20191009-private-bin.md

**Comment by hiroTochigi** [comment]
@xavierh93 The second error is 100% my fault. I forgot to put `.` 
The correct command is `docker build -t privatebin .`

The first error is weird.
I do not know why the error message tells `APT-GET`.
The command should be `apt-get`. 
Could you send me your Dockerfile? 
I would like to look at it.

**Comment by XavierElon** [comment]
@hiroTochigi oh okay. And yes I'll send it shortly.

**Review by CalebProvost — APPROVED** [review]

**Review by dogi — APPROVED** [review]

**Pull request merged**
