### PR TITLE
capitalize word in gitrepositories.md (fixes #683)

### LINKED ISSUE #683: Capitalization issue in gitrepositories.md
### Problem
Under "Understand that there are three levels of a Github respository", "the" isn't capitalized in "the upstream".

 ### Steps to reproduce the problem
Go to https://treehouses.io/#!./pages/vi/gitrepositories.md

 ### Screenshots
error4

 ### Proposed solution
Capitalize "the" which changes the bullet to The upstream (treehouses.github.io)

### PR DESCRIPTION
**Pull request by leosp123**
Fixes #683 

### Description
Capitalizes "the" in "the upstream"

### Raw.Githack preview link
raw.githack link to page(s) changed.

https://raw.githack.com/leosp123/leosp123.github.io/capitalize-section/#!pages/vi/gitrepositories.md

### CODE REVIEW

**Review by sydneyaldo — CHANGES_REQUESTED** [review]
githubandroidstudiowindows.md shouldn't be modified

**Comment by avin-sharma** [comment]
@leosp123 Something similar happened to me when I opened up the project in VS Code, `githubandroidstudiowindows.md` would show up as a modified file and it won't let me discard the changes for some reason.

**Comment by anthonyhvo12** [comment]
@leosp123 @avin-sharma I'm facing the same issue. The 20200610-githubandroidstudiowindows.md file is shown as modified and Github won't let me discard the changes. I have tried git reset --hardHEAD and git rm --cached -r as suggested by some tutorials but to no luck.

**Comment by avin-sharma** [comment]
I have not opened a pull request, but I added just my profile to the commit and pushed it (basically ignored the other modified file). If nothing works you could start over and instead of doing `add .`, you could do `add filename` and then commit.

**Comment by warthog16** [comment]
Maybe try creating another pull request with only one file committed as @avin-sharma said

**Pull request closed without merging**
