### PR TITLE
create Daves1245.md

### PR DESCRIPTION
**Pull request by Daves1245**
raw.githack link:
https://raw.githack.com/MontgomeryJukebox/MontgomeryJukebox.github.io/MJ-MDwiki/#!pages/vi/profiles/MontgomeryJukebox.md

### CODE REVIEW

**Review by law-lin — DISMISSED** [review]
I see the bolded words, but can't seem to decipher it...

**Comment by dogi** [comment]
> I see the bolded words, but can't seem to decipher it...

@law-lin I can't see them in githack

**Comment by dogi** [comment]
@Daves1245 please rename your file the same way as your `<githubname>.md`

anyhow nice start

but think mdwiki can't show your secret with bold ...

**Comment by kjong** [comment]
It's barely visible (but I guess that's the point).

**Comment by Daves1245** [comment]
When I took a gander at the githack I thought I could see it. Maybe I'm biased, but it's just a reference to the european white elm tree so not that important.

**Review by LordJashin32 — APPROVED** [review]
https://raw.githack.com/MontgomeryJukebox/MontgomeryJukebox.github.io/MJ-MDwiki/#!pages/vi/profiles/Daves1245.md

**Review by dogi — APPROVED** [review]
good job @Daves1245 ;)

**Pull request merged**
