### PR TITLE
Step7

### PR DESCRIPTION
**Pull request by ArranHL**
This section will cover Next Cloud and Tor browser/installation to get the VI's familiar with OLE's  file service.

### CODE REVIEW

**Review by dogi — APPROVED** [review]

**Review by dogi — CHANGES_REQUESTED** [review]
@Liew211 think we need you here ;)

**Comment by Liew211** [comment]
@dogi Do you suggest linking directly to the blog post, or creating another page similar to it, more tailored to the steps?

**Comment by dogi** [comment]
@Liew211 good question

think we should start with linking to blog post and in addition make them rename the rpi to their github name and then turn tor notice on ... all done by treehouses remote ;)

**Comment by Liew211** [comment]
@dogi Using treehouses remote would just be for introducing them to it right? Because I think generally from a dev perspective ssh from a computer would be better

**Comment by Liew211** [comment]
@dogi And since things like change name and notice on only makes sense for VIs, not random people trying it out, I can just copy the blogpost file and make the changes for those.

**Comment by dogi** [comment]
@Liew211 bingo I do not want you to change anything onto to blog post ;)

and yes we should offer both solutions ssh and treehouses remote (yes we introduce romote to them in earlier steps as we do with ssh)

**Comment by Liew211** [comment]
@dogi @ArranHL I'll do this and make commits on this branch/PR then

**Review by dogi — APPROVED** [review]

**Pull request merged**
