### PR TITLE
update faq.md (fixes #318)

### LINKED ISSUE #318: inappropriate word ( bad language )  "Shit"  in faq.md
### Problem
I found an<code> inappropriate word</code> ( bad language )<strong> "Shit" </strong>in the <code>faq.md</code> file under the section Helpful Links ---> Reference/Advanced ---><code>"Oh,Shit,Git"</code> .  I think its not a good way to express it like that, especially when we have new interns it might fall into a negative perception at the treehouses project and it looks very unprofessionell.
### Steps to reproduce the problem

N/A

### Screenshots

Oh_shit_git

### Proposed solution

Go in the file https://treehouses.io/#!./pages/vi/faq.md and edit and fix it and rename it to : <strong>more references</strong>

### PR DESCRIPTION
**Pull request by jamjakpa**
Fixes #319

### Description
- The website called ... [Oh, S***, Git](http://ohshitgit.com/)

### Raw.Githack preview link
raw.githack link to page(s) changed.

https://raw.githack.com/jamjakpa/jamjakpa.github.io/oh_git_fixed/#!./pages/vi/faq.md

### CODE REVIEW

**Comment by irisb1701** [comment]
looks good!

**Comment by irisb1701** [comment]
I think markdown isn't recognizing the other 2 asterisk, if you look at the raw.githack link it shows `oh, s*, git` Maybe change it to just `Oh, Sh*t, Git`. Also change the title, remove 319 and include (fixes #318)

**Comment by jamjakpa** [comment]
all fixed !

**Review by irisb1701 — APPROVED** [review]

**Comment by jamjakpa** [comment]
> I think markdown isn't recognizing the other 2 asterisk, if you look at the raw.githack link it shows oh, s*, git Maybe change it to just Oh, Sh*t, Git. Also change the title, remove 319 and include (fixes #318)

all fixed !

**Review by kjong — APPROVED** [review]

**Pull request merged**
