### PR TITLE
create jgeffrard.md

### PR DESCRIPTION
**Pull request by ghost**
### Raw.Githack preview link
https://raw.githack.com/jgeffrard/jgeffrard.github.io/my-new-branch/#!pages/vi/profiles/jgeffrard.md

### CODE REVIEW

**Review by kjong — APPROVED** [review]

**Review by LordJashin32 — DISMISSED** [review]
This might be borderline. I think 5 different type of elements was the requirement. 2 of the elements are headers and a different list. I don't know if that counts. I would add a link and a bold. And then that'd be perfect

**Comment by ghost** [comment]
Should I submit another pull request?

Thanks for the feedback!

**Comment by LordJashin32** [comment]
> Should I submit another pull request?
> 
> Thanks for the feedback!

Should be able to add the changes right here from files -> edit. Etc. Up to you how you want to do it. 
No need for new PR if you can help it.

**Comment by ghost** [comment]
Okay, I made the changes!

**Review by dogi — APPROVED** [review]

**Review by LordJashin32 — APPROVED** [review]

**Pull request merged**
