### PR TITLE
Create jamjakpa.md

### PR DESCRIPTION
**Pull request by jamjakpa**
Fixes #issue_number
1
### Description
I have created the Raw.Githack link. but for some reason it shows up a 404 error ?

### Raw.Githack preview link

https://rawcdn.githack.com/jamjakpa/jamjakpa.github.io/31343c5808d81b7e454fdde573865c55496af4fd/pages/vi/profiles/jamjakpa.md

### CODE REVIEW

**Review by pattanawadee88 — CHANGES_REQUESTED** [review]
please put the right raw.githack link for us to review and don't work on your master branch 
This is the right link https://raw.githack.com/jamjakpa/jamjakpa.github.io/master/#!pages/vi/profiles/jamjakpa.md

**Comment by jamjakpa** [comment]
> please put the right raw.githack link for us to review and don't work on your master branch
> This is the right link https://raw.githack.com/jamjakpa/jamjakpa.github.io/master/#!pages/vi/profiles/jamjakpa.md

Okay i will do it later on in my break , thank you for helping me

**Comment by pattanawadee88** [comment]
> > please put the right raw.githack link for us to review and don't work on your master branch
> > This is the right link https://raw.githack.com/jamjakpa/jamjakpa.github.io/master/#!pages/vi/profiles/jamjakpa.md
> 
> Okay i will do it later on in my break , thank you for helping me

please let me know if you need help :)

**Comment by jamjakpa** [comment]
> > > please put the right raw.githack link for us to review and don't work on your master branch
> > > This is the right link https://raw.githack.com/jamjakpa/jamjakpa.github.io/master/#!pages/vi/profiles/jamjakpa.md
> > 
> > 
> > Okay i will do it later on in my break , thank you for helping me
> 
> please let me know if you need help :)

yes i need help . I get confused with the master. and where do I add the raw.githack. link . it shows 404 .
Thank you so much for your help :) . How can i make sure that i don't use the master. I have read bu ti think it missed it .

**Comment by pattanawadee88** [comment]
> > > > please put the right raw.githack link for us to review and don't work on your master branch
> > > > This is the right link https://raw.githack.com/jamjakpa/jamjakpa.github.io/master/#!pages/vi/profiles/jamjakpa.md
> > > 
> > > 
> > > Okay i will do it later on in my break , thank you for helping me
> > 
> > 
> > please let me know if you need help :)
> 
> yes i need help . I get confused with the master. and where do I add the raw.githack. link . it shows 404 .
> Thank you so much for your help :) . How can i make sure that i don't use the master. I have read bu ti think it missed it .

you put the raw.githack link in your PR. The raw.githack link is for us to review your work, you do not need to put in the link anywhere else. 

And here is the format of the raw.githack link :
https://raw.githack.com/{YourGitHubUsername}/{YourGitHubUsername}.github.io/{YourBranchName}/#!index.md

This is what I mean by master branch
Screen Shot 2019-11-25 at 1 43 32 PM


So to fix it, you should create a new branch before working.
Screen Shot 2019-11-25 at 1 48 29 PM

**Comment by jamjakpa** [comment]
> > > > > please put the right raw.githack link for us to review and don't work on your master branch
> > > > > This is the right link https://raw.githack.com/jamjakpa/jamjakpa.github.io/master/#!pages/vi/profiles/jamjakpa.md
> > > > 
> > > > 
> > > > Okay i will do it later on in my break , thank you for helping me
> > > 
> > > 
> > > please let me know if you need help :)
> > 
> > 
> > yes i need help . I get confused with the master. and where do I add the raw.githack. link . it shows 404 .
> > Thank you so much for your help :) . How can i make sure that i don't use the master. I have read bu ti think it missed it .
> 
> you put the raw.githack link in your PR. The raw.githack link is for us to review your work, you do not need to put in the link anywhere else.
> 
> And here is the format of the raw.githack link :
> [https://raw.githack.com/{YourGitHubUsername}/{YourGitHubUsername}.github.io/{YourBranchName}/#!index.md](https://raw.githack.com/%7BYourGitHubUsername%7D/%7BYourGitHubUsername%7D.github.io/%7BYourBranchName%7D/#!index.md)
> 
> This is what I mean by master branch
> Screen Shot 2019-11-25 at 1 43 32 PM
> 
> So to fix it, you should create a new branch before working.
> Screen Shot 2019-11-25 at 1 48 29 PM
So nice of you that you help :) what do you mean by PR ?

**Comment by pattanawadee88** [comment]
> > > > > > please put the right raw.githack link for us to review and don't work on your master branch
> > > > > > This is the right link https://raw.githack.com/jamjakpa/jamjakpa.github.io/master/#!pages/vi/profiles/jamjakpa.md
> > > > > 
> > > > > 
> > > > > Okay i will do it later on in my break , thank you for helping me
> > > > 
> > > > 
> > > > please let me know if you need help :)
> > > 
> > > 
> > > yes i need help . I get confused with the master. and where do I add the raw.githack. link . it shows 404 .
> > > Thank you so much for your help :) . How can i make sure that i don't use the master. I have read bu ti think it missed it .
> > 
> > 
> > you put the raw.githack link in your PR. The raw.githack link is for us to review your work, you do not need to put in the link anywhere else.
> > And here is the format of the raw.githack link :
> > [https://raw.githack.com/{YourGitHubUsername}/{YourGitHubUsername}.github.io/{YourBranchName}/#!index.md](https://raw.githack.com/%7BYourGitHubUsername%7D/%7BYourGitHubUsername%7D.github.io/%7BYourBranchName%7D/#!index.md)
> > This is what I mean by master branch
> > Screen Shot 2019-11-25 at 1 43 32 PM
> > So to fix it, you should create a new branch before working.
> > Screen Shot 2019-11-25 at 1 48 29 PM
> > So nice of you that you help :) what do you mean by PR ?

PR = Pull Request 
No problem :)

**Comment by jamjakpa** [comment]
> > > > > > > please put the right raw.githack link for us to review and don't work on your master branch
> > > > > > > This is the right link https://raw.githack.com/jamjakpa/jamjakpa.github.io/master/#!pages/vi/profiles/jamjakpa.md
> > > > > > 
> > > > > > 
> > > > > > Okay i will do it later on in my break , thank you for helping me
> > > > > 
> > > > > 
> > > > > please let me know if you need help :)
> > > > 
> > > > 
> > > > yes i need help . I get confused with the master. and where do I add the raw.githack. link . it shows 404 .
> > > > Thank you so much for your help :) . How can i make sure that i don't use the master. I have read bu ti think it missed it .
> > > 
> > > 
> > > you put the raw.githack link in your PR. The raw.githack link is for us to review your work, you do not need to put in the link anywhere else.
> > > And here is the format of the raw.githack link :
> > > [https://raw.githack.com/{YourGitHubUsername}/{YourGitHubUsername}.github.io/{YourBranchName}/#!index.md](https://raw.githack.com/%7BYourGitHubUsername%7D/%7BYourGitHubUsername%7D.github.io/%7BYourBranchName%7D/#!index.md)
> > > This is what I mean by master branch
> > > Screen Shot 2019-11-25 at 1 43 32 PM
> > > So to fix it, you should create a new branch before working.
> > > Screen Shot 2019-11-25 at 1 48 29 PM
> > > So nice of you that you help :) what do you mean by PR ?
> 
> PR = Pull Request
> No problem :)

I am also stuck with the pull request from where do request the pull request

**Comment by pattanawadee88** [comment]
> > > > > > > > please put the right raw.githack link for us to review and don't work on your master branch
> > > > > > > > This is the right link https://raw.githack.com/jamjakpa/jamjakpa.github.io/master/#!pages/vi/profiles/jamjakpa.md
> > > > > > > 
> > > > > > > 
> > > > > > > Okay i will do it later on in my break , thank you for helping me
> > > > > > 
> > > > > > 
> > > > > > please let me know if you need help :)
> > > > > 
> > > > > 
> > > > > yes i need help . I get confused with the master. and where do I add the raw.githack. link . it shows 404 .
> > > > > Thank you so much for your help :) . How can i make sure that i don't use the master. I have read bu ti think it missed it .
> > > > 
> > > > 
> > > > you put the raw.githack link in your PR. The raw.githack link is for us to review your work, you do not need to put in the link anywhere else.
> > > > And here is the format of the raw.githack link :
> > > > [https://raw.githack.com/{YourGitHubUsername}/{YourGitHubUsername}.github.io/{YourBranchName}/#!index.md](https://raw.githack.com/%7BYourGitHubUsername%7D/%7BYourGitHubUsername%7D.github.io/%7BYourBranchName%7D/#!index.md)
> > > > This is what I mean by master branch
> > > > Screen Shot 2019-11-25 at 1 43 32 PM
> > > > So to fix it, you should create a new branch before working.
> > > > Screen Shot 2019-11-25 at 1 48 29 PM
> > > > So nice of you that you help :) what do you mean by PR ?
> > 
> > 
> > PR = Pull Request
> > No problem :)
> 
> I am also stuck with the pull request from where do request the pull request

after fixing the issues, you need to create a PR.

**Comment by jamjakpa** [comment]
> > > > > > > > > please put the right raw.githack link for us to review and don't work on your master branch
> > > > > > > > > This is the right link https://raw.githack.com/jamjakpa/jamjakpa.github.io/master/#!pages/vi/profiles/jamjakpa.md
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Okay i will do it later on in my break , thank you for helping me
> > > > > > > 
> > > > > > > 
> > > > > > > please let me know if you need help :)
> > > > > > 
> > > > > > 
> > > > > > yes i need help . I get confused with the master. and where do I add the raw.githack. link . it shows 404 .
> > > > > > Thank you so much for your help :) . How can i make sure that i don't use the master. I have read bu ti think it missed it .
> > > > > 
> > > > > 
> > > > > you put the raw.githack link in your PR. The raw.githack link is for us to review your work, you do not need to put in the link anywhere else.
> > > > > And here is the format of the raw.githack link :
> > > > > [https://raw.githack.com/{YourGitHubUsername}/{YourGitHubUsername}.github.io/{YourBranchName}/#!index.md](https://raw.githack.com/%7BYourGitHubUsername%7D/%7BYourGitHubUsername%7D.github.io/%7BYourBranchName%7D/#!index.md)
> > > > > This is what I mean by master branch
> > > > > Screen Shot 2019-11-25 at 1 43 32 PM
> > > > > So to fix it, you should create a new branch before working.
> > > > > Screen Shot 2019-11-25 at 1 48 29 PM
> > > > > So nice of you that you help :) what do you mean by PR ?
> > > 
> > > 
> > > PR = Pull Request
> > > No problem :)
> > 
> > 
> > I am also stuck with the pull request from where do request the pull request
> 
> after fixing the issues, you need to create a PR.

could you please check if i have fixed it i created new branch not master , and can you check if you can see my profile now :)  to me it shows always as 408 error

**Comment by jamjakpa** [comment]
> > > > > > > > > > please put the right raw.githack link for us to review and don't work on your master branch
> > > > > > > > > > This is the right link https://raw.githack.com/jamjakpa/jamjakpa.github.io/jamjakpa-patch-1/#!index.md

> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > Okay i will do it later on in my break , thank you for helping me
> > > > > > > > 
> > > > > > > > 
> > > > > > > > please let me know if you need help :)
> > > > > > > 
> > > > > > > 
> > > > > > > yes i need help . I get confused with the master. and where do I add the raw.githack. link . it shows 404 .
> > > > > > > Thank you so much for your help :) . How can i make sure that i don't use the master. I have read bu ti think it missed it .
> > > > > > 
> > > > > > 
> > > > > > you put the raw.githack link in your PR. The raw.githack link is for us to review your work, you do not need to put in the link anywhere else.
> > > > > > And here is the format of the raw.githack link :
> > > > > > [https://raw.githack.com/{YourGitHubUsername}/{YourGitHubUsername}.github.io/{YourBranchName}/#!index.md](https://raw.githack.com/%7BYourGitHubUsername%7D/%7BYourGitHubUsername%7D.github.io/%7BYourBranchName%7D/#!index.md)
> > > > > > This is what I mean by master branch
> > > > > > Screen Shot 2019-11-25 at 1 43 32 PM
> > > > > > So to fix it, you should create a new branch before working.
> > > > > > Screen Shot 2019-11-25 at 1 48 29 PM
> > > > > > So nice of you that you help :) what do you mean by PR ?
> > > > 
> > > > 
> > > > PR = Pull Request
> > > > No problem :)
> > > 
> > > 
> > > I am also stuck with the pull request from where do request the pull request
> > 
> > 
> > after fixing the issues, you need to create a PR.
> 
> could you please check if i have fixed it i created new branch not master , and can you check if you can see my profile now :) to me it shows always as 408 error

here is the new created one with a branch not master 
https://github.com/jamjakpa/jamjakpa.github.io/blob/jamjakpa-patch-1/pages/vi/profiles/jamjakpa.md

**Comment by jamjakpa** [comment]
branch is jamjakpa-patch-1

**Comment by pattanawadee88** [comment]
You should read the First Steps very carefully :) this is my suggestion 
https://treehouses.io/#!pages/vi/firststeps.md#Step_0_-_Introductory_Steps
Or watching youtube for additional help

**Comment by jamjakpa** [comment]
> You should read the First Steps very carefully :) this is my suggestion
> https://treehouses.io/#!pages/vi/firststeps.md#Step_0_-_Introductory_Steps
> Or watching youtube for additional help

okay will do later . I will start form the beginning again

**Comment by jamjakpa** [comment]
> You should read the First Steps very carefully :) this is my suggestion
> https://treehouses.io/#!pages/vi/firststeps.md#Step_0_-_Introductory_Steps
> Or watching youtube for additional help

so i did it again and link it with raw .but it says page not found : 
https://raw.githack.com//jamjakpa/jamjakpa.github.io/jamjakpa_1_branch/#!pages/vi/profiles/jamjakpa.md

**Pull request closed without merging**
