### PR TITLE
create avin-sharma.md

### PR DESCRIPTION
**Pull request by avin-sharma**
### Description
Created avin-sharma.md

### Raw.Githack preview link
https://raw.githack.com/avin-sharma/avin-sharma.github.io/add-avin-sharma/#!pages/vi/profiles/avin-sharma.md

### CODE REVIEW

**Comment by jayala-29** [comment]
@dogi

**Review by sydneyaldo — COMMENTED** [review]
Pretty good but 1 more markdown element would be nice

**Comment by warthog16** [comment]
Nice changes!

**Review by warthog16 — APPROVED** [review]

**Comment by avin-sharma** [comment]
Added a GIF and a blockquote, please take a look!

**Review by sydneyaldo — APPROVED** [review]

**Review by anastasia21112 — APPROVED** [review]

**Pull request merged**
