### PR TITLE
gk-web.md

### PR DESCRIPTION
**Pull request by ghost**
https://raw.githack.com/gk-web/gk-web.github.io/git-checkout--b-new-code/#!pages/vi/profiles/gk-web.md

### CODE REVIEW

**Comment by dogi** [comment]
> [raw.githack.com/gk-web/gk-web.github.io/git-checkout--b-new-code/#!pages/vi/profiles/gk-web.md](https://raw.githack.com/gk-web/gk-web.github.io/git-checkout--b-new-code/#!pages/vi/profiles/gk-web.md)

@gk-web you should check above link and will see that 3 `::::` things to not work with mdwiki
just copy in the special character ;)

**Comment by gk-web** [comment]
* I am Gautam Khanna situated in Waterloo, ON, Canada { ⏰ ▶️   Eastern Daylight Time (EDT)}.
* I am currently pursuing *ECE* in **University of Waterloo** and I am really passionate about coding.
* My Hobbies are:
  1. Listening to Music 🎶 
  2. Programming
    * C/C++
    * Python
  3. Sports 🏓 
* And, I am very excited about this new OLE project and I hope we achieve the mission with perfection.

**Comment by ghost** [comment]
@dogi I have made some changes, please view it again and let me know. Thanks!

**Comment by XavierElon** [comment]
Hi, the link is not working.

**Pull request closed without merging**
