### PR TITLE
blog outline (fixes #154)

### LINKED ISSUE #154: Add description of blogs
On the blogs page before the list of blogposts and after the header, there should be some kind of introduction paragraph describing the purpose of the blogs, i.e. "these are blog posts written by virtual interns on projects they have worked on at treehouses" etc etc

### PR DESCRIPTION
**Pull request by phamduchongan93**
Basic description for the blog. This changed is used to fix #154. It is meant to clarify the info for the blog.

### CODE REVIEW

**Comment by dogi** [comment]
@phamduchongan93 can you add raw githack link

**Comment by phamduchongan93** [comment]
Look at [Raw Githack](https://raw.githack.com/treehouses/treehouses.github.io/blog_outline/#!pages/blog/list.md)

**Comment by Liew211** [comment]
@phamduchongan93 @dogi I made a commit, take a look if you guys can.  This was my original idea behind issue #154 , I thought it would be better to have some kind of intro like this.

I was also wondering, would it look better to add bullet points for the blog entries?

**Review by Liew211 — APPROVED** [review]

**Comment by phamduchongan93** [comment]
Hmm, I will add the bullet points to see how it looks

**Comment by phamduchongan93** [comment]
@Liew211 look at 
https://raw.githack.com/treehouses/treehouses.github.io/blog_outline/#!pages/blog/list.md 
I looks better indeed. :)

**Review by dogi — APPROVED** [review]

**Pull request merged**
