### PR TITLE
create amirajnigam.md

### PR DESCRIPTION
**Pull request by amirajnigam**
Fixes #issue_number

### Description
Description of changes made.

### Raw.Githack preview link
raw.githack link to page(s) changed.

e.g. https://raw.githack.com/UserName/Repository/Branch/Path/To/File.md

### CODE REVIEW

**Review by jayala-29 — CHANGES_REQUESTED** [review]
please update your PR description to reflect:
- what is the purpose of your file
- the correct githack link to display your `.md` file via url

**Comment by amirajnigam** [comment]
Please check. I have made the required changes.

**Comment by kjong** [comment]
You should update the description of the pull request itself. Not commit a separate link.

**Comment by dogi** [comment]
close due inactivity

**Pull request closed without merging**
