### PR TITLE
Update 20191014-kolibri.md

### PR DESCRIPTION
**Pull request by irisb1701**
https://raw.githack.com/treehouses/treehouses.github.io/update_kolibri/#!./pages/blog/20191014-kolibri.md

-check for grammatical/spelling/capitalization errors 
- Use of language regarding docker/ if explanation makes sense

### CODE REVIEW

**Comment by pattanawadee88** [comment]
I think you put in the wrong link.

https://raw.githack.com/treehouses/treehouses.github.io/update_kolibri/#!pages/blog/list.md

https://raw.githack.com/treehouses/treehouses.github.io/update_kolibri/#!./pages/blog/20191014-kolibri.md

**Review by kjong — CHANGES_REQUESTED** [review]
## Issues with "Run Kolibri using Autorunonce"

1. > This is optional, however you can Cmd/ctrl + F for the phrase 'start planet' and replace it with 'start services' since we are running both planet and kolibri now instead of just planet

Does this mean that ALL instances of `startplanet` in the autorunonce file should be replaced with `startservices`?
I am assuming that this is just changing the variable name to more accurately reflect the fact that more than one service is being run now.

---
2. When talking about setting up internet login settings, maybe include that you should also change `wifiname=""`? Should be fairly obvious but just in case...

---
3. When adding `treehouses tor add 8080`, should `starttor="false"` be changed to `starttor="true"` above?

---
4. A bit (actually very) nit-picky, but maybe change line 8 "boot file" to "boot folder".

---
5. Line 4
> This new line `echo "docker-compose -f /boot/kolibri.yml -p kolibri up -d"` will create a docker container for kolibri using a kolibri.yml file

This line that we are supposed to be adding to the autorunonce file is different from the line that is being added in the code block above (`echo "docker-compose -f /srv/kolibri/kolibri.yml -p kolibri up -d"`). I think that the correct line is the one in line 4 (the one with `boot/kolibri.yml`)?

---
6. Line 8
> Save this file with a .yml extension and place it inside your boot file

Does it matter what name the file is saved as? I am assuming that this file should be named "kolibri.yml" in accordance with the line that we are adding to the autorunonce file.

---
7. Another very nit-picky issue, but on the last line of the code block on line 6, version: "2"`,

is that ` at the very end a typo?

---
8. How long does it take after making all the configuration edits and starting up the raspberry pi for it to complete setting up (ie. solid green led)? Maybe include a time estimate in line 9?

**Review by kjong — APPROVED** [review]

**Comment by pattanawadee88** [comment]
after rebooting 
```
root@treehouses:~# docker ps 
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS              PORTS                                        NAMES
a9c4b4fcfa71        treehouses/planet:local    "/usr/bin/entry.sh /…"   About an hour ago   Up 23 minutes       0.0.0.0:80->80/tcp, 443/tcp                  planet_planet_1
b142913152f9        treehouses/couchdb:2.3.1   "tini -- /docker-ent…"   2 months ago        Up 23 minutes       4369/tcp, 9100/tcp, 0.0.0.0:2200->5984/tcp   planet_couchdb_1
```

**Comment by LordJashin32** [comment]
All grammatical errors will be found out!
https://raw.githack.com/treehouses/treehouses.github.io/d9b757828aebb33730d949a9ad6e972d2bbf3373/#!./pages/blog/20191014-kolibri.md

**Review by LordJashin32 — APPROVED** [review]

**Comment by LordJashin32** [comment]
> 
> 
> after rebooting
> 
> ```
> root@treehouses:~# docker ps 
> CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS              PORTS                                        NAMES
> a9c4b4fcfa71        treehouses/planet:local    "/usr/bin/entry.sh /…"   About an hour ago   Up 23 minutes       0.0.0.0:80->80/tcp, 443/tcp                  planet_planet_1
> b142913152f9        treehouses/couchdb:2.3.1   "tini -- /docker-ent…"   2 months ago        Up 23 minutes       4369/tcp, 9100/tcp, 0.0.0.0:2200->5984/tcp   planet_couchdb_1
> ```

Yeah, Docker containers have to be removed. They will be there until they are removed. This tutorial doesn't mention anything about removing them. Perhaps I add it now. 
https://raw.githack.com/treehouses/treehouses.github.io/34ce7de24ace1a2b2d9dc7ae1572a9ba390204a0/#!./pages/blog/20191014-kolibri.md

**Comment by kjong** [comment]
@LordJashin32 

Adding the `rm` command is a good addition.
However, this blog post is currently in limbo.
There's a possibility it may be scrapped or completely rewritten.

**Pull request closed without merging**
