### PR TITLE
direct navbar home button to index.md (fixes #456)

### LINKED ISSUE #456: navbar button redirects to 404 in index.html
### Problem
In the navigation bar at the top of the page, the home button directs the user to https://treehouses.io/# which temporarily brings the user to the 404 page before they are redirected to the home page.

 ### Steps to reproduce the problem
Visit any page on the markdown wiki and click on the treehouses.io button at the top left of the navigation bar. Click it in quick succession to see the redirect page temporarily show.

 ### Screenshots
gFNm6jB

 ### Proposed solution
Change line 2853 of index.html from:
`navbar += '<a class="navbar-brand" href="#"></a>'; ` 
to:
`navbar += '<a class="navbar-brand" href="#!index.md"></a>';`

### PR DESCRIPTION
**Pull request by ComputerOnFire**
Fixes #456

### Description
changed the home button so that it directs to index.md

### Raw.Githack preview link
https://raw.githack.com/ComputerOnFire/ComputerOnFire.github.io/navbar-fix/index.html
https://raw.githack.com/ComputerOnFire/ComputerOnFire.github.io/navbar-fix/mdwiki/js/bootstrap.js

### CODE REVIEW

**Review by LordJashin32 — APPROVED** [review]
Nice.

**Review by LordJashin32 — APPROVED** [review]
Nice.

**Review by dogi — APPROVED** [review]

**Review by paulbert — COMMENTED** [review]
Please also update `mdwiki/js/bootstrap.js` because that is one of many files used to build `index.html`.

Don't want to block this by setting "Request Changes", so I'll leave that up to @dogi & @LordJashin32

**Comment by ComputerOnFire** [comment]
added the change to bootstrap.js as well

**Comment by dogi** [comment]
thanks @ComputerOnFire 

@paulbert is this what we wanted ... ?

**Pull request merged**
