### PR TITLE
cleaning up index page to put JS and CSS in seperate folders, adding …

### PR DESCRIPTION
**Pull request by kheyrasantos**
cleaning up index page to put JS and CSS in seperate folders, adding overflow hidden to get rid of overflow on mobile

### CODE REVIEW

**Comment by CalebProvost** [comment]
Thank  you @kheyrasantos.
I'm not able to see the page render correctly however:
https://raw.githack.com/kheyrasantos/treehouses.github.io/master/index.html
nor https://raw.githack.com/kheyrasantos/treehouses.github.io/master/#!index.md

**Review by CalebProvost — CHANGES_REQUESTED** [review]
Resolve issue noted above.

**Review by Nietak — APPROVED** [review]

**Review by Nietak — COMMENTED** [review]
Super

**Review by hiroTochigi — DISMISSED** [review]
image
From your repository, it does not render correctly.
image
It is treehouses.
The only difference of two URLs are treehouses or kheyrasantos.
I think that something prevents rendering.

https://raw.githack.com/treehouses/treehouses.github.io/master/#!pages/vi/firststeps.md#Step_0_-_Introductory_Steps
https://raw.githack.com/kheyrasantos/treehouses.github.io/master/#!pages/vi/firststeps.md#Step_0_-_Introductory_Steps

**Comment by dogi** [comment]
@kheyrasantos feel free to reopen it ;)

**Pull request closed without merging**
