### PR TITLE
Update trackprogress.md (fixes #550)

### LINKED ISSUE #550: Find a better way than Default Username in Prompt Box
### Problem
There is an unnecessary default username in the prompt box when going to track your progress. I believe this was done during development to test but was forgotten about. 

 ### Steps to reproduce the problem
Go to the [Track Progress page](https://treehouses.io/#!pages/vi/trackprogress.md) and click the blue button.

 ### Screenshots
image

 ### Proposed solution
Change the initial value of the variable `user` in trackprogress.md from "dogi" to "Replace me with your GitHub username".

### PR DESCRIPTION
**Pull request by piyush-sharma**
Fixes #550 

### Description
Changed the initial value of the `user` variable from "dogi" to "Replace me with your GitHub username".

### Raw.Githack preview link
http://raw.githack.com/piyush-sharma-OLE/piyush-sharma-OLE.github.io/prompt_default_username_fix/#!pages/vi/trackprogress.md

### CODE REVIEW

**Review by jayala-29 — APPROVED** [review]

**Review by LordJashin32 — APPROVED** [review]

**Review by dogi — CHANGES_REQUESTED** [review]
:)

**Comment by dogi** [comment]
@piyush-sharma I know that you are kinda right,
but there are so many other thing you can fix ...

I mean in that `javascript`

**Comment by LordJashin32** [comment]
> @piyush-sharma I know that you are kinda right,
> but there are so many other thing you can fix ...
> 
> I mean in that `javascript`

Maybe we put some1 else there. Maybe the first contributor. ;) . Or the one with the longest name.

**Comment by dogi** [comment]
@piyush-sharma I wanted to change all of this to some other text,
but I can't edit ... maybe that is a bigger issue to work on
we want to be able to edit your PR so it will take less time to be able to merge ...

image

**Comment by dogi** [comment]
image

**Comment by piyush-sharma** [comment]
I made the change you suggested @dogi

**Comment by dogi** [comment]
> @piyush-sharma I wanted to change all of this to some other text,
> but I can't edit ... maybe that is a bigger issue to work on
> we want to be able to edit your PR so it will take less time to be able to merge ...
> 
> image


@piyush-sharma please work on this ... create an issue and then a PR

https://treehouses.io/#!./pages/vi/githubandmarkdown.md

**Pull request closed without merging**
