### PR TITLE
Profile Creation for CalebProvost & #79 Resolution

### PR DESCRIPTION
**Pull request by CalebProvost**
Resolved issue pertaining to Step 3’s reference of a solution/alternative in the FAQ page; created response which explains what to do.
Created my profile and added associated photo into the images directory.

[Link for visualization](https://raw.githack.com/CalebProvost-OLE/CalebProvost-OLE.github.io/CalebP-profile/#!pages/vi/profiles/CalebProvost.md)

### CODE REVIEW

**Comment by Liew211** [comment]
@CalebProvost Looks good, but please split your changes into separate pull requests - one for your profile, and one for your fix for #79

**Comment by CalebProvost** [comment]
Sorry about that. Should I do that now or in the future?

**Comment by Liew211** [comment]
Best if you do it now :)

**Comment by CalebProvost** [comment]
Closing to reopen with split branch.

**Pull request closed without merging**
