### PR TITLE
update github-issues.md (fixes #549)

### LINKED ISSUE #549: Comprehensive Information to Delete a Branch
### Problem
In the GitHub Issues page, bullet points 2 and 3 under "Deleting the Branch" are not clear.

 ### Steps to reproduce the problem
N/A

 ### Screenshots
Screen Shot 2020-04-25 at 12 29 42 AM

 ### Proposed solution

1. Switch to the master branch using `git checkout master` as you cannot be **on** the branch you want to delete.

2. Delete local branch using `git branch -d branch-name`.

3. Delete remote branch using `git push origin --delete branch-name`.

### PR DESCRIPTION
**Pull request by saurabh-mish**
Fixes #549 

### Description
Added information to the delete branch section

### Raw.Githack preview link
raw.githack link to page(s) changed:-

https://raw.githack.com/saura8h/saura8h.github.io/delete-branch-instructions/#!pages/vi/github-issues.md

### CODE REVIEW

**Review by LordJashin32 — DISMISSED** [review]
Not sure about this one totally yet but I think we can keep the part about delete-branch.png ? You didn't even remove the image from the images folder so maybe you were unsure about this as well. Maybe just replace the **Delete the branch from your local** part and keep **Delete the branch from your remote**

I'll ask the other team members and see what they think tomorrow. Cheers.

**Comment by saurabh-mish** [comment]
I do have a question about this fix. If you follow along the proposed solution [here](https://github.com/treehouses/treehouses.github.io/issues/549) the user will only be able to perform steps 1, 6, and 7. Steps 2, 3, 4, and 5 would be done by moderators/reviewers.

If you confirm this, I will remove steps 2, 3, 4, and 5 (from the proposed solution of the issue) along with the image.

**So the final proposed solution would be**:-

1. Switch to the master branch using `git checkout master` as you cannot be on the branch you want to delete.

2. Delete local branch using `git branch -d branch-name`.

3. Delete remote branch using `git push origin --delete branch-name`.

Please let me know.

**Comment by LordJashin32** [comment]
> I do have a question about this fix. If you follow along the proposed solution [here](https://github.com/treehouses/treehouses.github.io/issues/549) the user will only be able to perform steps 1, 6, and 7. Steps 2, 3, 4, and 5 would be done by moderators/reviewers.
> 
> If you confirm this, I will remove steps 2, 3, 4, and 5 (from the proposed solution of the issue) along with the image.
> 
> **So the final proposed solution would be**:-
> 
> 1. Switch to the master branch using `git checkout master` as you cannot be on the branch you want to delete.
> 2. Delete local branch using `git branch -d branch-name`.
> 3. Delete remote branch using `git push origin --delete branch-name`.
> 
> Please let me know.

Yeah i think I ran into this issue when I was a VI and forgot about it. I think the delete branch button doesn't work because they aren't part of the team yet? I will just take your word for it. 
EDIT: You still need to delete the image though. If we don't need it anymore.

**Comment by saurabh-mish** [comment]
Removed the delete-branch image.

@LordJashin32 the way I'm thinking about this is that we get a good amount of exposure to git command line by the time we raise the required number of pull requests.

Delete branch from remote is being done through GUI, which IMO is inconsistent as we follow along from steps 5, 6, and eventually 8.

The commit I've just made is the one I've proposed in this thread above. I just followed them with one of my merged PRs. It works exaclty as expected, without doing anything on the GUI. 
I'm going to modify the proposed solution on the [#549 page](https://github.com/treehouses/treehouses.github.io/issues/549) as well.

**Review by dogi — APPROVED** [review]
@saura8h good job ... I am a big believer that `sometimes less is more`

**Review by kjong — APPROVED** [review]

**Pull request merged**
