### PR TITLE
create kajanajustin.md

### PR DESCRIPTION
**Pull request by kajanajustin**
https://raw.githack.com/kajanajustin/kajanajustin.github.io/personal/#!pages/vi/profiles/kajanajustin.md

### CODE REVIEW

**Review by CalebProvost — COMMENTED** [review]
Looks good. Were you trying to inject some javascript onto your page?

**Comment by kajanajustin** [comment]
> Looks good. Were you trying to inject some javascript onto your page?

Yeah I attempted, but dosen't look like i got it to be how I wanted

**Comment by kajanajustin** [comment]
Ok I fixed it let me know if anything else needs editing!

**Review by CalebProvost — CHANGES_REQUESTED** [review]
It appears its still not injecting your prompt coding you're aiming for.
I don't know much about python, but I can point you in the right direction for the javascript.

You'll need to inject the javascript into the html (which is what loads the .md files), so you'll essentially need to have the script written as if its being written for html to work. 

[Give this a view](https://www.w3schools.com/html/html_scripts.asp) and try something similar to it.
I would recommend writing the code as a comment to first explain what it does. This way it's visible and explained for those who don't know/understand it. I recommend [this to practice](https://www.w3schools.com/html/tryit.asp?filename=tryhtml_script) before you commit it as a replacement.

Alternatively, if you want to use a different markdown, that'll be okay too. Remember you have to use 5 different markdown styles. I so far see 4 in addition to the plain text.

**Comment by kajanajustin** [comment]
Ok I just used a different markdown I used italics, let me know if there is anything else you need from me. Also is there anything else I can do while I wait for my Raspberry Pi to come in the mail?

**Review by CalebProvost — APPROVED** [review]

**Comment by CalebProvost** [comment]
> Ok I just used a different markdown I used italics, let me know if there is anything else you need from me. Also is there anything else I can do while I wait for my Raspberry Pi to come in the mail?

Skipping to [Step 8](https://treehouses.io/#!./pages/vi/firststeps.md#Step_8_-_Create_Issues_and_Pull_Requests) would be about what is left without a RPi... which doesn't give you much for now. Best bet is to look over all the pages you can and see if there's anything that can be improved or expanded upon. Also, look over some [blogs](https://treehouses.io/#!pages/blog/list.md) and see if there's anything there that needs work.

**Review by dogi — APPROVED** [review]

**Pull request merged**
