### PR TITLE
Fix blog list typo (fixes #102)

### LINKED ISSUE #102: Redundancy typo in "list.md"
The line in github.io/pages/blog/list.md:
 > [treehouses.io in DevOpsDay Jakarta](20180505-devopsdayjkt18.md) 2018 on May 5, 2018 by empeje

should be:
 > [treehouses.io in DevOpsDay Jakarta](20180505-devopsdayjkt18.md) on May 5, 2018 by empeje

### PR DESCRIPTION
**Pull request by CalebProvost**
[GitHack for quick view](https://raw.githack.com/CalebProvost-OLE/CalebProvost-OLE.github.io/Fix%23102/#!pages/blog/list.md)

### CODE REVIEW

**Review by dogi — CHANGES_REQUESTED** [review]
@CalebProvost there are 2 pictures which should not be there

**Comment by dogi** [comment]
tip use `git rm ...`

**Comment by dogi** [comment]
anyhow more important don't branch from a branch ... only branch from master

**Comment by CalebProvost** [comment]
Sorry about that.

**Comment by CalebProvost** [comment]
I'm not sure if the accidental branching was resolved or not, but I performed the request to remove the photos.

**Review by dogi — APPROVED** [review]

**Pull request merged**
