### PR TITLE
Trackprogress #199

### PR DESCRIPTION
**Pull request by sonAndrew**
* Added function to get Comments from api.github.com

### CODE REVIEW

**Comment by dogi** [comment]
@sonAndrew first fly over there are 3 images from an older PR which have nothing to do with this one ... did you branch from master? is master broken?

**Comment by sonAndrew** [comment]
@dogi I did branch from master but I don't think it is broken let me check what happened.

**Comment by CalebProvost** [comment]
Don't forget the githack link:
https://raw.githack.com/sonAndrew/sonAndrew.github.io/trackprogress/#!pages/vi/trackprogress.md

**Review by CalebProvost — APPROVED** [review]

**Comment by sriharivishnu** [comment]
@sonAndrew 
The function is not returning the correct number of comments... 
In your function, you use the following link to search for comments:
`https://api.github.com/search/issues?q=repo:treehouses/treehouses.github.io+author:"+user+"+type:comment&sort=created&order=asc`

However, Github Search API does not have a `type:comment` query. Right now it is returning all search results in the repository (Issues and PRs) pertaining to the user, and is not returning number of comments. To prove this, you can see that the number of comments returned by your function is always the sum of the numbers of PRs and Issues. For example, @dogi apparently has 25 comments, but really it is 18 Issues + 7 PRs that are giving this number.

**The Reason:**
Github Search API does not recognize the type:comment query. In fact, you could put any query in type and you get the same number back:

For example, observe the following links with type queries `type:test123`, and `type:comment`:

- https://api.github.com/search/issues?q=repo:treehouses/treehouses.github.io+author:dogi+type:test123&sort=created&order=asc
- https://api.github.com/search/issues?q=repo:treehouses/treehouses.github.io+author:dogi+type:comment&sort=created&order=asc

They both return 25 results, as it is only searching for PRs and Issues under the specified username, **not comments**.
Please refer to my original comment on the Issue for a suggested approach.

**Review by CalebProvost — CHANGES_REQUESTED** [review]
Looks like I didn't test it thoroughly enough.

I recommend the approach that @sriharivishnu has suggested in issue #199 
However, I also suggest putting more effort into other PRs which will count towards you joining the internship as this is a more lengthy PR in of itself. Albeit, needed.

**Pull request closed without merging**
