### PR TITLE
Clarify multiple container conflict (fixes #104)

### LINKED ISSUE #104: Add stop Docker container clarification for Nextcloud (Step 7)
In order to avoid containers from conflicting and causing issues with tor loading Nextcloud, if would be helpful to add a clarification clause to:
> Now that the container has been created, you can stop and start it with `docker stop nextcloud` and `docker start nextcloud`. To view all running and stopped containers, run `docker ps -a`.

Something like:
> Note: use `docker stop <container>` on any running containers other than Nextcloud.

### PR DESCRIPTION
**Pull request by CalebProvost**
Added clarification just before **Start up Tor**

[GitHack for Quick View](https://raw.githack.com/CalebProvost-OLE/CalebProvost-OLE.github.io/Fix%23104/#!pages/vi/nextcloud-tor.md)

### CODE REVIEW

**Comment by dogi** [comment]
@CalebProvost rereading the instructions it looks like you did not followed them in an exact way ... ;)

cause in line 14 it says you should flash a new image ...
think there we should add the info
to use an other new sdcard

**Comment by dogi** [comment]
maybe it should be a Note (in markdown it will be in a blue frame) where we explain the reason why we want multiple sdcards ...

... so we can run multple experiments ;)

**Comment by CalebProvost** [comment]
I'm confused. I did flash to a second SD card. 
I was referencing docker containers. Only one should be active.

**Comment by dogi** [comment]
> I'm confused. I did flash to a second SD card.
> I was referencing docker containers. Only one should be active.

hmm did you redo `autorunonce` in boot partition?

**Comment by lmmrssa** [comment]
> I'm confused. I did flash to a second SD card.
> I was referencing docker containers. Only one should be active.

Yes if you have another container running same port then it will have conflict. Which seems to be the case with you as you flash new SD card but also did autorunonce which will start Planet. So putting note not to do autorunonce could help
@dogi What is your view on this? We ask not to do autorunonce or we ask them to look on containers and stop other containers?

**Comment by dogi** [comment]
thx @lmmrssa yes would be a conflict if planet was active,
when redoing `autorunonce` there should be no planet containers
maybe the new `autorunonce` did not get saved @CalebProvost ;)

**Comment by lmmrssa** [comment]
@CalebProvost looks like you missed `In your file explorer, navigate to the boot drive, and open the autorunonce file in a text editor of your choice. Delete everthing, and paste this in:` this part :)

**Comment by CalebProvost** [comment]
> thx @lmmrssa yes would be a conflict if planet was active,
> when redoing `autorunonce` there should be no planet containers
> maybe the new `autorunonce` did not get saved @CalebProvost ;)

@lmmrssa I remember writing it. So there's a good chance it didn't save/I forgot to hit ctrl+s as @dogi suspects. The reason I think that's the case was because when I checked via ssh, the file had changed to `autoranonce` but what it contained was not what I wrote. 

Should I do this step again? I do have everything running now, but I'm not sure if there are other stuff affected by the bad save.

Back on the topic of this PR; should it be removed?
I'm thinking of changing it to a note to help guide others with diagnose and how to fix the conflict if they encounter "_Planet Learning_".
In example:
> NOTE: If _Tor_ loads "_Planet Learning_" run `docker ps -a` and check if any other containers are present and running. If they are, stop the containers by using the command `docker stop <ContainerName>`, then reboot and try again.

**Comment by dogi** [comment]
> Should I do this step again? I do have everything running now, but I'm not sure if there are other stuff affected by the bad save.

no

**Comment by dogi** [comment]
think more we should make note in the beginning
where we tell people to make sure that `autorunonce` was written ;)

**Review by dogi — APPROVED** [review]
@CalebProvost awesome

**Review by hiroTochigi — APPROVED** [review]

**Review by lmmrssa — APPROVED** [review]

**Pull request merged**
