### PR TITLE
update team.md

### PR DESCRIPTION
**Pull request by sriharivishnu**
Added **sriharivishnu** to team.md. 

Rawgit: https://raw.githack.com/sriharivishnu/sriharivishnu.github.io/sriharivishnu/#!pages/vi/team.md

### CODE REVIEW

**Review by CalebProvost — APPROVED** [review]
Final review before merge to be done by @dogi

**Review by XavierElon — APPROVED** [review]
Good job

**Review by dogi — CHANGES_REQUESTED** [review]
@sriharivishnu congrats

-> on hold until interview

**Review by dogi — APPROVED** [review]
congrats @sriharivishnu :)

**Pull request merged**
