### PR TITLE
step1: note for password on bridge hotspot (fixes #311)

### LINKED ISSUE #311: open hotspot
### Problem
The instructions to install wifi also set up the RPI as a hot spot but without a password. This is convenient but I just dont want my neighbors using my bandwidth to watch netflix.

### Steps to reproduce the problem
Complete the steps 1 through 12 for [using treehouses remote](https://treehouses.io/#!./pages/vi/treehouses-remote.md). And view the new "treehouses" hotspot on your phone or laptop.

### Screenshots
Before Solution:
treehousesInsecure

After Solution:
treehousesSecure

### Proposed solution
Recommend changing step 11 to read something like:

11. Back in the terminal type `treehouses bridge "wifiname" treehouses "wifipassword" "hotspot-password"`, and replace wifiname with the name of your wifi network, wifipassword with the password for your wifi, and hotspot-password with a new password for the hotspot being created.

### PR DESCRIPTION
**Pull request by john-dunbar**
Fixes #311

### Description
This update improves the bridge command on step 11 by adding a user defined hotspot password.

### Raw.Githack preview link

https://raw.githack.com/dun08015/dun08015.github.io/make-hotspot-secure/#!./pages/vi/treehouses-remote.md

### CODE REVIEW

**Review by phamduchongan93 — COMMENTED** [review]
revising

**Review by kjong — APPROVED** [review]

**Comment by irisb1701** [comment]
looks good, good call on the punctuation

**Review by irisb1701 — APPROVED** [review]

**Review by dogi — CHANGES_REQUESTED** [review]
@dun08015 generally I like that think we should add a password onto our bridge hotspot, but for seek of lowering the barrier to entry we want first to show a open wifi hotspot

maybe you can add a note about the option of password

**Comment by LordJashin32** [comment]
After the first wave of an open SSID. The user can go to the app and change the wifi password for the hotspot there. This app is open source and OLE is focused on learning, and ease of use. There doesn't seem to be an overarching "need" for heightened security. I for one love security and love to keep it at the highest possible for myself but it's not for "everyone". 

Edit: I fear the Virtual Intern directions becoming too long, but I guess in the case of Virtual Interns they are here to learn/work anyway. So I support adding directions to the wiki for this.

**Comment by john-dunbar** [comment]
@dogi Okay, sounds good. I'll make it into a note instead.
@LordJashin32 I agree the main purpose is to make learning easier and having passwords creates a barrier. Personally, I would prefer to have the security of a password. I'm going to make a note in case anyone else is unsure how to do so.

**Review by dogi — APPROVED** [review]

**Pull request merged**
