### PR TITLE
create siddarthorke.md

### PR DESCRIPTION
**Pull request by siddarthorke**
### Description
Create siddarthorke.md

### Raw.Githack preview link
raw.githack link to page(s) changed.

https://raw.githack.com/siddarthorke/siddarthorke.github.io/siddarth-orke/#!pages/vi/profiles/siddarthorke.md

### CODE REVIEW

**Review by LordJashin32 — APPROVED** [review]
Spookin me out. Your githack link isn't working and I can't figure out why. Anyway. Looks good. As soon as that's fixed should be ready to go.

**Comment by siddarthorke** [comment]
Hey @LordJashin32, thanks for reaching out. I was trying to figure that out too! I thought I'd move forward and circle back at a later time. Maybe then, I'd figure out why.

**Comment by kjong** [comment]
Is it just me or are the emojis not displaying?

**Comment by LordJashin32** [comment]
Not displaying for me either. Otherwise looks good.

**Review by dogi — APPROVED** [review]

**Comment by ghost** [comment]
can someone unsubscribe or block me from this subscription?

**Comment by ghost** [comment]
i cant unsubscribe for some reason

**Comment by ghost** [comment]
kick me out if u have to?

**Pull request merged**
