### PR TITLE
Add fork me ribbon (fix #70)

### LINKED ISSUE #70: add a fork me on github somewhere
best would be top right corner ;)

### PR DESCRIPTION
**Pull request by phamduchongan93**
Add **fork me** ribbon on the right of treehouses webpage. It close issue #70.
[Raw Githack Link](https://raw.githack.com/phamduchongan93/phamduchongan93.github.io/add_fork_me/#!index.md)

### CODE REVIEW

**Comment by phamduchongan93** [comment]
Bare with me here. It seems like `git pull` command from upstream doesn't fix my master branch issue, therefore I had to remove the whole directory and fork treehouses github again.

**Comment by dogi** [comment]
> Bare with me here. It seems like `git pull` command from upstream doesn't fix my master branch issue, therefore I had to remove the whole directory and fork treehouses github again.

@phamduchongan93 looks like it works now ;)

**Comment by dogi** [comment]
@phamduchongan93 wonder if you can also change the color of the ribbon from red to the navigation bar blue

**Comment by phamduchongan93** [comment]
MDwiki supports that.  BLue it is then

**Review by dogi — APPROVED** [review]

**Comment by phamduchongan93** [comment]
Unfortunately, MD gimmick only support these color set  'red', 'darkblue', 'green', 'orange', 'white', 'gray' [Source](http://dynalon.github.io/mdwiki/#!gimmicks.md)

**Review by lmmrssa — APPROVED** [review]

**Pull request merged**
