### PR TITLE
update treehouses-remote.md (fixes #506)

### LINKED ISSUE #506: Consistent Bluetooth and Raspberry Pi disconnects
### Problem
For some people, they may have an unstable connection between their Android device and their Raspberry Pi. 

 ### Steps to reproduce the problem
I used a OnePlus 6T phone with 8GB RAM, Android version 10, and OxygenOS version 10.3.2. I used treehouses remote to connect to my Raspberry Pi via Bluetooth. There was a connection for the first 20 seconds or so, then it would disconnect. This was consistent for every attempted connection.

 ### Proposed solution
For me, I just kept reconnecting to my RPI and entered the terminal commands.  This likely isn't the ideal fix for my problem, but it worked in the end.

I'm not quite sure how to solve these constant disconnects, but a **NOTE** could be added that states:
If you are experiencing frequent Bluetooth disconnects, keep on trying to "Connect to RPI" and enter the commands into the terminal.

### PR DESCRIPTION
**Pull request by law-lin**
Fixes #506 

### Description
Added a note to suggest restarting device if they are experiencing frequent Bluetooth disconnects.
I'm not sure how to render the note properly in mdwiki (I just followed the example of the previous notes).

### Raw.Githack preview link
http://raw.githack.com/law-lin-OLE/law-lin-OLE.github.io/treehouses-remote-note/#!pages/vi/treehouses-remote.md

### CODE REVIEW

**Review by LordJashin32 — APPROVED** [review]

**Comment by LordJashin32** [comment]
Note needs to be on same line though.

**Review by dogi — APPROVED** [review]

**Comment by dogi** [comment]
> Note needs to be on same line though.

@law-lin I would have fixed this for you, but when you created the PR you did remove the right for us where we could change/fix your PR ...

... in other words you are making your life more difficult by not allowing us to help you ;)

**Comment by law-lin** [comment]
I still cannot find the option to let others fix my PR. Is this because this repository is in an organization that I created?

**Comment by dogi** [comment]
> I still cannot find the option to let others fix my PR. Is this because this repository is in an organization that I created?

think you can only do that when you create the PR
anyhow @law-lin no worries the fix we need is trivial ... just go for it ;)

**Comment by law-lin** [comment]
@dogi Alright, I fixed it

**Comment by LordJashin32** [comment]
Still needs fixing i think:

**Review by dogi — APPROVED** [review]

**Pull request merged**
