### PR TITLE
team pictures added (fixes #333)

### LINKED ISSUE #333: add Github profile pics
Right now there isn't any **Github profile pictures** on the website for any of the **Virtual Interns**. We can change this with an image tag. I'm not sure how this affects **copyright**. I assume its okay because Github owns and hosts the website anyway and they require no copyright notice according to https://github.com/logos.

Cheers.

### PR DESCRIPTION
**Pull request by LordJashin32**
Fixes #333 

### Description
Added Github profile pictures with image tag width and height of 50 pixels

### Raw.Githack preview link
https://raw.githack.com/LordJashin32/lordjashin32.github.io/302c140b51b7e949cdf84e8d36c381ba16df19bd/#!pages/vi/retiredinterns.md
https://raw.githack.com/LordJashin32/lordjashin32.github.io/302c140b51b7e949cdf84e8d36c381ba16df19bd/#!pages/vi/team.md

### CODE REVIEW

**Review by kjong — APPROVED** [review]

**Comment by dogi** [comment]
@LordJashin32 nice idea ...
anyhow we will for now set this PR on hold
-> it requires some further discussion

please work on something else

**Review by dogi — DISMISSED** [review]
on hold

**Comment by LordJashin32** [comment]
https://raw.githack.com/LordJashin32/lordjashin32.github.io/2b74ab4f8c606d0e5ea03a95be0259b474947358/#!pages/vi/retiredinterns.md
https://raw.githack.com/LordJashin32/lordjashin32.github.io/2b74ab4f8c606d0e5ea03a95be0259b474947358/#!pages/vi/team.md

**Comment by LordJashin32** [comment]
Okay finally done check links above. Cheers.

**Review by dogi — APPROVED** [review]

**Pull request merged**
